name: zephyr
description: zephyr by claret

publish_to: 'none' 

version: 2.0.2+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  http: 
  dynamic_color:
  geolocator: 
  geocoding: 
  home_widget:
  flutter_foreground_task: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  generate: true
  uses-material-design: true