name: easyweather
description: easyweather by claret

publish_to: 'none' 

version: 2.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  http: 
  permission_handler: 
  # geolocator: 
  # geocoding: 
  date_format:
  dynamic_color:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true