name: easyweather
description: easyweather by claret

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 
  get: 
  http: 
  permission_handler: 
  geolocator: 
  geocoding: 
  date_format:
  expandable_text:
  cupertino_icons:
  flutter_z_location:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true

  assets:
   - assets/images/cloudy.jpg
   - assets/images/foggy.jpg
   - assets/images/rainy.jpg
   - assets/images/overcast.jpg
   - assets/images/snowy.gif
   - assets/images/windy.gif
   - assets/images/sunny.jpg

  fonts:
    - family: HMOS
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf