name: easyweather
description: easyweather by claret

publish_to: 'none' 

version: 1.1.5+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  get: 
  http: 
  permission_handler: 
  geolocator: 
  geocoding: 
  date_format:
  dynamic_color:
  expandable_text:
  cupertino_icons:
  flutter_secure_storage:
  url_launcher:
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:

  uses-material-design: true

  assets:
   - assets/images/cloudy.jpg
   - assets/images/foggy.jpg
   - assets/images/rainy.jpg
   - assets/images/overcast.jpg
   - assets/images/snowy.gif
   - assets/images/windy.gif
   - assets/images/sunny.jpg