import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Map<String,IconData> weatherIcons = {
    '晴' : Icons.sunny,
    '少云' : Icons.cloud,
    '晴间多云' : CupertinoIcons.cloud_sun,
    '平静' : Icons.clear_all_rounded,
    '多云' : Icons.cloud,
    '有风' : CupertinoIcons.wind,
    '微风' : CupertinoIcons.wind,
    '和风' : CupertinoIcons.wind,
    '清风' : CupertinoIcons.wind,
    '强风' : CupertinoIcons.wind,
    '疾风' : CupertinoIcons.wind,
    '大风' : CupertinoIcons.wind,
    '烈风' : CupertinoIcons.wind,
    '风暴' : CupertinoIcons.tornado,
    '狂爆风' : CupertinoIcons.tornado,
    '飓风' : CupertinoIcons.tornado,
    '热带风暴' : CupertinoIcons.tornado,
    '霾' : CupertinoIcons.infinite,
    '中度霾' : CupertinoIcons.infinite,
    '重度霾' : CupertinoIcons.infinite,
    '严重霾' : CupertinoIcons.infinite,
    '阴' : CupertinoIcons.cloud,
    '阵雨' : CupertinoIcons.cloud_rain,
    '雷阵雨' : CupertinoIcons.cloud_bolt_rain_fill,
    '雷阵雨并伴有冰雹' : CupertinoIcons.cloud_hail_fill,
    '小雨' : CupertinoIcons.cloud_rain,
    '中雨' : CupertinoIcons.cloud_rain,
    '大雨' : CupertinoIcons.cloud_heavyrain_fill,
    '暴雨' : CupertinoIcons.cloud_heavyrain_fill,
    '大暴雨' : CupertinoIcons.cloud_heavyrain_fill,
    '特大暴雨' : CupertinoIcons.cloud_heavyrain_fill,
    '强阵雨' : CupertinoIcons.cloud_heavyrain_fill,
    '强雷阵雨' : CupertinoIcons.cloud_bolt_rain_fill,
    '极端降雨' : CupertinoIcons.cloud_heavyrain_fill,
    '雨' : CupertinoIcons.cloud_rain,
    '雾' : CupertinoIcons.cloud_fog_fill,
    '雪'  : Icons.snowing,
    '阵雪'  : Icons.snowing,
    '小雪'  : Icons.snowing,
    '中雪': CupertinoIcons.cloud_snow,
    '大雪': CupertinoIcons.cloud_snow_fill,
    '暴雪': CupertinoIcons.cloud_snow_fill,
    '雨夹雪' : CupertinoIcons.cloud_sleet,
};

Map<String,String> weatherBackground = {
  '晴' : "assets/images/sunny.jpg",
  '少云' : "assets/images/cloudy.jpg",
  '晴间多云' : "assets/images/cloudy.jpg",
  '平静' : "assets/images/sunny.jpg",
  '多云' : "assets/images/cloudy.jpg",
  '有风' : "assets/images/cloudy.jpg",
  '微风' : "assets/images/cloudy.jpg",
  '和风' : "assets/images/cloudy.jpg",
  '清风' : "assets/images/cloudy.jpg",
  '强风' : "assets/images/windy.gif",
  '疾风' : "assets/images/windy.gif",
  '大风' : "assets/images/windy.gif",
  '烈风' : "assets/images/windy.gif",
  '风暴' : "assets/images/windy.gif",
  '狂爆风' : "assets/images/windy.gif",
  '飓风' : "assets/images/windy.gif",
  '热带风暴' : "assets/images/windy.gif",
  '霾' : "assets/images/foggy.jpg",
  '中度霾' : "assets/images/foggy.jpg",
  '重度霾' : "assets/images/foggy.jpg",
  '严重霾' : "assets/images/foggy.jpg",
  '阴' : "assets/images/overcast.jpg",
  '阵雨' : "assets/images/rainy.jpg",
  '雷阵雨' : "assets/images/rainy.jpg",
  '雷阵雨并伴有冰雹' : "assets/images/rainy.jpg",
  '小雨' : "assets/images/rainy.jpg",
  '中雨' : "assets/images/rainy.jpg",
  '大雨' : "assets/images/rainy.jpg",
  '暴雨' : "assets/images/rainy.jpg",
  '大暴雨' : "assets/images/rainy.jpg",
  '特大暴雨' : "assets/images/rainy.jpg",
  '强阵雨' : "assets/images/rainy.jpg",
  '强雷阵雨' : "assets/images/rainy.jpg",
  '极端降雨' : "assets/images/rainy.jpg",
  '雨' : "assets/images/rainy.jpg",
  '雾' : "assets/images/foggy.jpg",
  '雪'  : "assets/images/snowy.gif",
  '阵雪'  : "assets/images/snowy.gif",
  '小雪'  : "assets/images/snowy.gif",
  '中雪': "assets/images/snowy.gif",
  '大雪': "assets/images/snowy.gif",
  '暴雪': "assets/images/snowy.gif",
  '雨夹雪' : "assets/images/snowy.gif",
};

Map<String,String> weeks = {
    '1' : '星期一',
    '2' : '星期二',
    '3' : '星期三',
    '4' : '星期四',
    '5' : '星期五',
    '6' : '星期六',
    '7' : '星期日',
};